language: go
sudo: false
go:
- 1.8.3
install:
- go get -t ./...
- go get -u honnef.co/go/tools/cmd/gosimple
before_script:
- go fmt ./...
- go vet ./...
- gosimple ./...
script:
# - go test -i -race ./...
# - go test -v -race ./...